stages:
  - lint
  - test
  - prod

eslint:
  stage:
    lint
  script:
  - npm install
  - npm run eslint
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - node_modules/
  except:
  - master
  tags:
  - docker

test:
  stage:
    test
  script:
  - npm install
  - node_modules/.bin/gulp clean
  - node_modules/.bin/gulp dist
  - rsync -avzP dist/ root@test.thorgene.com:/srv/docker/thorgene-mweb-nginx/html/
  - ssh root@test.thorgene.com "docker-compose -f /root/thorgene-mweb-fe-docker/docker-compose.yml restart nginx"
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - node_modules/
  only:
  - master
  tags:
  - shell
  
prod:
  stage:
    prod
  script:
  - rsync -avzP . root@thorgene.com:/srv/docker/thorgene-mweb-nginx/mweb-src --exclude=node_modules --exclude=build --exclude=dist --delete
  - ssh root@thorgene.com "cd /srv/docker/thorgene-mweb-nginx/mweb-src && npm install && node_modules/.bin/gulp dist"
  only:
  - tags
  tags:
  - shell