stages:
  - lint
  - test
  - prod

eslint:
  stage:
    lint
  script:
  - npm install
  - node_modules/.bin/gulp lint
  cache:
    key: "node_modules_cache"
    paths:
    - node_modules/
  except:
  - master
  - tags
  tags:
  - docker
  
test:
  stage:
    test
  script:
  - npm install
  - NODE_ENV=test node_modules/.bin/webpack --config webpack/webpack.test.config.js
  - rsync -avzP build/ root@test.thorgene.com:/srv/docker/thorgene-mweb-nginx/html/
  cache:
    key: "node_modules_cache"
    paths:
    - node_modules/
  only:
  - /^test.*$/
  tags:
  - shell

test_cordova:
  stage:
    test
  script:
  - npm install
  - CORDOVA_ENV=true NODE_ENV=test node_modules/.bin/webpack --config webpack/webpack.test.config.js
  cache:
    key: "node_modules_cache"
    paths:
    - node_modules/
  artifacts:
    paths:
    - build/
  only:
  - /^test.*$/
  tags:
  - shell

prod:
  stage:
    prod
  script:
    - npm install
    - NODE_ENV=production node_modules/.bin/webpack --config webpack/webpack.prod.config.js
    - rsync -avzP --delete dist/ root@thorgene.com:/srv/docker/thorgene-mweb-nginx/html/thorgene-mweb-$CI_BUILD_REF_NAME/
  cache:
    key: "node_modules_cache"
    paths:
    - node_modules/
  only:
  - tags
  tags:
  - shell

prod_cordova:
  stage:
    prod
  script:
  - npm install
  - CORDOVA_ENV=true NODE_ENV=production node_modules/.bin/webpack --config webpack/webpack.prod.config.js
  cache:
    key: "node_modules_cache"
    paths:
    - node_modules/
  artifacts:
    paths:
    - dist/
  only:
  - tags
  tags:
  - shell