stages:
  - lint
  - test

eslint:
  stage:
    lint
  script:
  - npm install
  - npm run eslint
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - node_modules/
  except:
  - master
  tags:
  - docker

test:
  stage:
    test
  script:
  - npm install
  - node_modules/.bin/gulp clean
  - node_modules/.bin/gulp dist
  - rsync -avzP dist root@test.thorgene.com:/srv/docker/thorgene-mweb-nginx/html/
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - node_modules/
  only:
  - master
  tags:
  - shell